# Generated by Django 5.2.6 on 2025-11-20 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_venta_cantidad_vendida_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventadetalle',
            options={'ordering': ['venta', 'producto']},
        ),
    ]
